name: Deploy to Production

on:
  push:
    branches:
      - develop
      - main

# Permissões necessárias para o deploy
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install -g gh-pages
      
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh-pages -d . -b gh-pages
          
      - name: Check deployment
        run: |
          echo "Deploy concluído! O site deve estar atualizado em alguns minutos."
          echo "URL do site: https://${{ github.repository_owner }}.github.io/prestaconta-ampla/" 